{% set name = "pdal" %}
{% set version = "2.0.0" %}
{% set sha256 = "60d41da79441d0aa9c44ec6ebb7497ffc0090d761259d42d4eeb05c7146bb432" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-2.0.0.tar.gz
  url: https://github.com/PDAL/python/archive/2.0.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true   # [win]

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cython
    - numpy
    - libpdal >=1.7.1
    - packaging

  run:
    - python {{ python }}
    - cython
    - numpy
    - libpdal >=1.7.1

test:
  imports:
    - pdal

about:
  home: https://www.pdal.io/
  license: BSD
  summary: 'Point cloud data processing'

extra:
  recipe-maintainers:
    - mathieu1
