{% set name = "laszip" %}
{% set version = "3.2.2" %}
{% set sha256 = "0b2e5df3b4f464da9331dfc7bd455044a656be0f2251e50be5f087417ad41876" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/LASzip/LASzip/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
  run:

test:
  commands:
    - conda inspect linkages {{ name }}

about:
  home: http://www.laszip.org/
  license: LGPL
  summary: 'Free and lossless LiDAR compression'

extra:
  recipe-maintainers:
    - mathieu1
