{% set name = "lazperf" %}
{% set version = "1.1.0" %}
{% set sha256 = "5413bb3e727d8b7155900f35b8f5e487eee418957d251fb3799d2cd3e17b2158" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hobu/laz-perf/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cython
    - numpy >=1.11

  run:
    - python
    - cython
    - numpy >=1.11

test:
  imports:
    - lazperf

about:
  home: https://github.com/hobu/laz-perf/
  license: LGPL
  summary: 'Point cloud data compression'

extra:
  recipe-maintainers:
    - mathieu1
