{% set version = "1.9.1" %}
{% set sha256 = "b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3" %}

package:
    name: flann
    version: {{ version }}
source:
    fn: flann-{{ version }}.tar.gz
    sha256: {{ sha256 }}
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
build:
    number: 0
requirements:
    build:
        - hdf5
        - gcc
    run:
        - hdf5
        - libgcc
test:
    commands:
        - test -f $PREFIX/lib/libflann_s.a
        - test -f $PREFIX/lib/libflann.so
        - test -f $PREFIX/lib/libflann_cpp_s.a
        - test -f $PREFIX/lib/libflann_cpp.so
about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: The Fast Library for Approximate Nearest Neighbors
extra:
    recipe-maintainers:
        - jakevdp
        - jakirkham
        - mathieu1
